import 'bootstrap';
import './scss/style.scss';
import './assets/logo.png';
import './assets/minLogo.png';
import './assets/screens/douglas-prototype.jpg';
import './assets/screens/react-blog.jpg';
import './assets/screens/react-blog.jpg';
import './assets/screens/weather.jpg';
import './assets/screens/filmaria.jpg';
import './assets/screens/dougflix.jpg';
import './assets/screens/webpack.png';
import './assets/screens/node-mysql.jpeg';
import {iconDom, iconLibrary} from './icons';
